name: test

concurrency:
  group: ${{ startsWith(github.head_ref, 'renovate/') && format('renovate-{0}', github.head_ref) || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: "Node ${{ matrix.node }} / ${{ matrix.os }}"
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Run test
        run: |
          # npm において package-lock.json の optional dependencies を欠落するバグがあるらしく、削除した後に再インストールをする
          # @see https://nx.dev/troubleshooting/troubleshoot-nx-install-issues#native-modules
          # @see https://github.com/npm/cli/issues/4828
          rm package-lock.json
          npm install
          npm test
